FROM registry.cn-beijing.aliyuncs.com/opendcp/image-javaweb:latest
EXPOSE 8080
ENV CATALINA_HOME /usr/local/tomcat/apache-tomcat-7.0.78
MAINTAINER bppan
ENTRYPOINT exec /usr/local/tomcat/apache-tomcat-7.0.78/bin/catalina.sh run
